# Generated by Django 5.1.1 on 2024-10-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
